# Site settings
title: Yongtao Hu's blog
email:
description: "Keep it simple, and keep it real!"
baseurl: ""
url: "http://herohuyongtao.github.io"
github_username: herohuyongtao

# Build settings
markdown: kramdown
pygments: true
permalink: pretty
